services:

  postgres:
    image: postgres:16-alpine
    container_name: raglens_postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-raglens}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-raglens}
      POSTGRES_DB: ${POSTGRES_DB:-raglens}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-raglens} -d ${POSTGRES_DB:-raglens}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: raglens_qdrant

    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"

    volumes:
      - qdrant_data:/qdrant/storage


volumes:
  pg_data:
  qdrant_data: